# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: react frontend CI/CD
env:
  REACT_APP_API_DOMAIN: https://mydiary.yoelnozar.com
  REACT_APP_COGNITO_REDIRECT: https://mydiarycp.github.io/frontend
  REACT_APP_COGNITO: https://mydiary.auth.us-east-1.amazoncognito.com/login?client_id=48f5b7938qm4dnjfleknn07a3&response_type=token&scope=aws.cognito.signin.user.admin+email+openid+phone+profile&redirect_uri=
  CI: false
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  CI_Check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      # - run: npm ci
      - name: Install Packages # remember the frontend directory context
        # working-directory: ./frontend
        run: npm install --legacy-peer-deps
      - run: npm run lint
      - run: npm test --passWithNoTests
